//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TortillasReader.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TortillasReader.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to add an object already present..
        /// </summary>
        public static string CannotAddAlreadyExistingFile {
            get {
                return ResourceManager.GetString("CannotAddAlreadyExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot delete an object that does not exist..
        /// </summary>
        public static string CannotDeleteNonExistingFile {
            get {
                return ResourceManager.GetString("CannotDeleteNonExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot update an object that does not exist..
        /// </summary>
        public static string CannotUpdateNonExistingFile {
            get {
                return ResourceManager.GetString("CannotUpdateNonExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comic mode.
        /// </summary>
        public static string ComicMode {
            get {
                return ResourceManager.GetString("ComicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comics archives.
        /// </summary>
        public static string ComicsArchives {
            get {
                return ResourceManager.GetString("ComicsArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of commands.
        /// </summary>
        public static string CommandsList {
            get {
                return ResourceManager.GetString("CommandsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left/right arrows: Change page
        ///Double click: Zoom on the mouse
        ///Click and drag while zooming: Move around the image
        ///Load a file: Load a book
        ///Go to page: Move to the selected page
        ///Page scroll speed: Move pages 1 or 2 at a time
        ///Dark screen mode: Darkens the screen for eye comfort
        ///Double page mode: Displays only one image at a time to manage comics with double pages
        ///Comic mode: Changes the reading direction to go from manga mode to comic mode.
        /// </summary>
        public static string CommandsListFull {
            get {
                return ResourceManager.GetString("CommandsListFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark screen mode.
        /// </summary>
        public static string DarkScreenMode {
            get {
                return ResourceManager.GetString("DarkScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable animations.
        /// </summary>
        public static string DisableAnimations {
            get {
                return ResourceManager.GetString("DisableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double page mode.
        /// </summary>
        public static string DoublePageMode {
            get {
                return ResourceManager.GetString("DoublePageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file that was currently playing could not be found:
        ///.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to page.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos.
        /// </summary>
        public static string Infos {
            get {
                return ResourceManager.GetString("Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load a file.
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page scrolling speed.
        /// </summary>
        public static string PageScrollingSpeed {
            get {
                return ResourceManager.GetString("PageScrollingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tortillas reader -.
        /// </summary>
        public static string TortillasReader {
            get {
                return ResourceManager.GetString("TortillasReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsupported file format..
        /// </summary>
        public static string UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created by Tortillas - 2023
        ///url: https://github.com/tortillas5/TortillasReader.
        /// </summary>
        public static string WhoMadeThis {
            get {
                return ResourceManager.GetString("WhoMadeThis", resourceCulture);
            }
        }
    }
}
