//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TortillasReader.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TortillasReader.Resources.fr-FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;ajouter un objet déjà présent..
        /// </summary>
        public static string CannotAddAlreadyExistingFile {
            get {
                return ResourceManager.GetString("CannotAddAlreadyExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de supprimer un objet qui n&apos;existe pas..
        /// </summary>
        public static string CannotDeleteNonExistingFile {
            get {
                return ResourceManager.GetString("CannotDeleteNonExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de mettre à jour un objet qui n&apos;existe pas..
        /// </summary>
        public static string CannotUpdateNonExistingFile {
            get {
                return ResourceManager.GetString("CannotUpdateNonExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode comic.
        /// </summary>
        public static string ComicMode {
            get {
                return ResourceManager.GetString("ComicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archives de bandes dessinées.
        /// </summary>
        public static string ComicsArchives {
            get {
                return ResourceManager.GetString("ComicsArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des commandes.
        /// </summary>
        public static string CommandsList {
            get {
                return ResourceManager.GetString("CommandsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flèches de gauche / droite : Changer de page
        ///Double cliquer : Zoom sur la souris
        ///Cliquer et déplacer pendant le zoom : Se déplacer sur l&apos;image
        ///Charger un fichier : Charge un livre
        ///Aller à la page : Se déplacer à la page sélectionnée
        ///Vitesse de défilement des pages : Déplacer les pages par 1 ou 2 à la fois
        ///Mode écran sombre : Assombrit l&apos;écran pour le confort des yeux
        ///Mode double pages : N&apos;affiche qu&apos;une image à la fois pour gérer les comics avec des doubles pages
        ///Mode comic : Change le sens de lectu [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string CommandsListFull {
            get {
                return ResourceManager.GetString("CommandsListFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode écran sombre.
        /// </summary>
        public static string DarkScreenMode {
            get {
                return ResourceManager.GetString("DarkScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désactiver les animations.
        /// </summary>
        public static string DisableAnimations {
            get {
                return ResourceManager.GetString("DisableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode double pages.
        /// </summary>
        public static string DoublePageMode {
            get {
                return ResourceManager.GetString("DoublePageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier qui était en cours de lecture est introuvable :
        ///.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aller à la page.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos.
        /// </summary>
        public static string Infos {
            get {
                return ResourceManager.GetString("Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charger un fichier.
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vitesse de défilement des pages.
        /// </summary>
        public static string PageScrollingSpeed {
            get {
                return ResourceManager.GetString("PageScrollingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réglages.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tortillas reader -.
        /// </summary>
        public static string TortillasReader {
            get {
                return ResourceManager.GetString("TortillasReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du fichier non géré..
        /// </summary>
        public static string UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé par Tortillas - 2023
        ///url : https://github.com/tortillas5/TortillasReader.
        /// </summary>
        public static string WhoMadeThis {
            get {
                return ResourceManager.GetString("WhoMadeThis", resourceCulture);
            }
        }
    }
}
